# {{{
# Generated by zgen.
# This file will be overwritten the next time you run zgen save!

ZSH=/home/kristoffer/.zgen/robbyrussell/oh-my-zsh-master

# ### General modules
source "/home/kristoffer/.zgen/miekg/lean-master/lean.plugin.zsh"
source "/home/kristoffer/.zgen/zsh-users/zsh-autosuggestions-master/zsh-autosuggestions.plugin.zsh"
source "/home/kristoffer/.zsh/plugins/gpg-agent.plugin.zsh"
source "/home/kristoffer/.zgen/chrissicool/zsh-256color-master/zsh-256color.plugin.zsh"

# ### Plugins & Completions
fpath=(/home/kristoffer/.zgen/miekg/lean-master /home/kristoffer/.zgen/zsh-users/zsh-completions-master/src /home/kristoffer/.zgen/zsh-users/zsh-autosuggestions-master /home/kristoffer/.zsh/plugins /home/kristoffer/.zgen/chrissicool/zsh-256color-master ${fpath})

# }}}
